### ISSUE TITLE
cwa_use_credentials: false is not working  for role based installation

### ISSUE THREAD

**Issue by shuklaabhi** [christiangda/ansible-role-amazon-cloudwatch-agent#14]
Variable definition in vars/main.yml  redeclares it 
`cwa_use_credentials: "{{ true|bool if cwa_agent_mode == 'onPremise' }}"`

which should be something like (doesn't work though due to self-reference), idea is to retain original value, maybe you need to use two variables instead.

`cwa_use_credentials: "{{ true|bool if cwa_agent_mode == 'onPremise'   else cwa_use_credentials }}"`

so on ec2 mode, it will not be a boolean value, which would throw an error. It can also not be overridden in the playbook, the only way is passing the variable from the shell external variable.

**Comment by christiangda** [comment]
Hi @shuklaabhi , thank you for your ticket,  ASAP I'll release a new version with this fix.

**Comment by shuklaabhi** [comment]
Thanks a lot.

**Comment by shuklaabhi** [comment]
You can't reference a self variable, ansible has this bug. > {"msg": "The conditional check 'cwa_use_credentials' failed. The error was: An unhandled exception occurred while templating '{{ true|bool if cwa_agent_mode == 'onPremise' else cwa_use_credentials }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ true|bool if cwa_agent_mode == 'onPremise' else cwa_use_credentials }}'

Spin up a docker container and test it with a sample playbook.
docker run -v $(pwd):/project --name ubuntu_bash --rm -i -t ubuntu:18.04 bash
        "echo python3 -v ",
        "sudo apt-get -y upgrade",
        "sudo apt-get -y update",
        "sudo apt install -y python3-pip",
        "sudo pip3 install ansible==2.9"

- hosts: localhost
  connection: local
  gather_facts: true   
  become: yes           
  roles:
    - christiangda.amazon_cloudwatch_agent


ansible-playbook playbook.yml

**Comment by shuklaabhi** [comment]
I had mentioned the same in the bug itself.
