### ISSUE TITLE
amazon-ssm-agent install fails when yum has gpg checking enabled

### ISSUE THREAD

**Issue by kpankonen** [christiangda/ansible-role-amazon-cloudwatch-agent#3]
The amazon-ssm-agent rpm is not signed and fails to install when yum has gpg checking enabled.  Related issues: 
https://github.com/aws/amazon-ssm-agent/issues/28
https://github.com/aws/amazon-ssm-agent/issues/161

Setting `disable_gpg_check` to `yes` allows the install to succeed.  I think this is safe since the playbook is already using gpg to validate the downloaded file.

```
    amazon-ebs: TASK [christiangda.amazon_cloudwatch_agent : Install amazon-cloudwatch-agent.rpm] ***
    amazon-ebs: Friday 09 August 2019  18:26:40 -0400 (0:00:00.883)       0:06:44.637 *********
    amazon-ebs: FAILED - RETRYING: Install amazon-cloudwatch-agent.rpm (5 retries left).
    amazon-ebs: FAILED - RETRYING: Install amazon-cloudwatch-agent.rpm (4 retries left).
    amazon-ebs: FAILED - RETRYING: Install amazon-cloudwatch-agent.rpm (3 retries left).
    amazon-ebs: FAILED - RETRYING: Install amazon-cloudwatch-agent.rpm (2 retries left).
    amazon-ebs: FAILED - RETRYING: Install amazon-cloudwatch-agent.rpm (1 retries left).
    amazon-ebs: fatal: [127.0.0.1]: FAILED! => changed=false 
    amazon-ebs:   attempts: 5
    amazon-ebs:   changes:
    amazon-ebs:     installed:
    amazon-ebs:     - /tmp/amazon-cloudwatch-agent.rpm
    amazon-ebs:   msg: |2-
    amazon-ebs:   
    amazon-ebs:   
    amazon-ebs:     Package amazon-cloudwatch-agent.rpm is not signed
    amazon-ebs:   rc: 1
```

**Comment by TobiasRoland** [comment]
The aws cloudwatch provides a key: 

> https://s3.amazonaws.com/amazoncloudwatch-agent/assets/amazon-cloudwatch-agent.gpg

Would it not be possible to publish and provide a valid gpg key for ssm - is there a particular reason not to? The two referenced tickets have been closed, but I'm unsure as to the why of that - it makes it harder to convince clients, for instance, that we are installing trusted software only on a hybrid deployment
