### ISSUE TITLE
Latest release version tag format causes error during installation

### ISSUE THREAD

**Issue by bruno-canada** [christiangda/ansible-role-amazon-cloudwatch-agent#41]
The latest version format is using the prefix `v` which is different from the standard used so far by the repository. The inclusion of the prefix is causing the following error during installation:

```
[WARNING]: - christiangda.amazon_cloudwatch_agent was NOT installed successfully: Unable to compare role versions (1.0.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.1.0) to
determine the most recent version due to incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
```

The removal of the prefix will fix the problem. For others who are using `requirements.yml`, you can add the following until it is fixed:
```
- src: christiangda.amazon_cloudwatch_agent
  version: v2.1.0
```

FYI - @christiangda @alecpm

**Comment by christiangda** [comment]
hi, @bruno-canada thank you very much, sorry for this error.

I`m creating the right version one
