### ISSUE TITLE
collectd is not a required dependency

### ISSUE THREAD

**Issue by flickerfly** [christiangda/ansible-role-amazon-cloudwatch-agent#7]
I like the configuration experience, being able to put it into yaml directly in the playbook is a great way to get started and not get lost in JSON quotes and brace syntax stuff. 

collectd shouldn't be a required dependency as the CloudWatch agent only requires it if "collectd" is in the config. Otherwise, it is not expected. Could this be adjusted to not require this and therefore not require epel as well? 

To support this statement, I present this from the documentation. Also, I've had it running manually installed without collectd.

> The collectd software is not installed automatically on every server. For more information, see the Download page for collectd.
> 
> To collect these custom metrics, add a "collectd": {} line to the metrics_collected section of the agent configuration file.

https://docs.aws.amazon.com/en_pv/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-collectd.html

**Comment by christiangda** [comment]
Thank you @flickerfly I'll take those into consideration for the next release.

In the next release, I'll decouple "christiangda.epel_repo" and the creation of the "aws cli profile".

To create an "aws cli profile" I created the new role https://galaxy.ansible.com/christiangda/awscli_configure
